agent:
  station_id: 7860f893-996d-477c-adac-b24e655a7d03
  station_name: PC-LENOVO
backend:
  api_url: http://10.0.0.240:8000/api/v1
  heartbeat_interval: 30
  reconnect_interval: 5
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZ2VudF83ODYwZjg5My05OTZkLTQ3N2MtYWRhYy1iMjRlNjU1YTdkMDMiLCJzdGF0aW9uX2lkIjoiNzg2MGY4OTMtOTk2ZC00NzdjLWFkYWMtYjI0ZTY1NWE3ZDAzIiwidHlwZSI6ImFnZW50IiwiZXhwIjoxNzkyNzgyMTczLCJpYXQiOjE3NjEyNDYxNzN9.xajs9LMq5YyxaZ4r7Os9Q4OcG8l3AlocArdldU5Pjls
  url: ws://10.0.0.240:8000/ws/agent
features:
  auto_lock: true
  auto_logout: true
  block_shutdown: true
  show_notifications: true
session:
  check_interval: 10
  grace_period: 60
  warning_time: 300
system:
  log_backup_count: 5
  log_file: agent.log
  log_level: INFO
  log_max_size: 10485760
  monitor_interval: 60
